/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutDialog: typeof import('./src/components/menu/AboutDialog.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    ContextMenu: typeof import('primevue/contextmenu')['default']
    CustomMarker: typeof import('./src/components/flow/edge/CustomMarker.vue')['default']
    DBConnectionDialog: typeof import('./src/components/sidebar/DBConnectionDialog.vue')['default']
    DBToolbar: typeof import('./src/components/sidebar/DBToolbar.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    EdgeWithButton: typeof import('./src/components/flow/edge/EdgeWithButton.vue')['default']
    FeedbackDialog: typeof import('./src/components/menu/FeedbackDialog.vue')['default']
    FlowCanvas: typeof import('./src/components/flow/FlowCanvas.vue')['default']
    FlowSearch: typeof import('./src/components/flow/search/FlowSearch.vue')['default']
    FlowTabs: typeof import('./src/components/flow/FlowTabs.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LeftSidebar: typeof import('./src/components/sidebar/LeftSidebar.vue')['default']
    PageItem: typeof import('./src/components/sidebar/PageItem.vue')['default']
    PageMenuManager: typeof import('./src/components/sidebar/PageMenuManager.vue')['default']
    RelationshipSelector: typeof import('./src/components/flow/edge/RelationshipSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SidebarTree: typeof import('./src/components/sidebar/SidebarTree.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TableNode: typeof import('./src/components/flow/TableNode.vue')['default']
    TableViewDialog: typeof import('./src/components/common/TableViewDialog.vue')['default']
    TopMenu: typeof import('./src/components/menu/TopMenu.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
