// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get(arg1) {
  return window['go']['api']['AppCacheApi']['Get'](arg1);
}

export function Init(arg1) {
  return window['go']['api']['AppCacheApi']['Init'](arg1);
}

export function Set(arg1, arg2) {
  return window['go']['api']['AppCacheApi']['Set'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['api']['AppCacheApi']['SetContext'](arg1);
}
