// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {service} from '../models';
import {connect} from '../models';

export function ClearTableVOCacheByTableID(arg1:number):Promise<void>;

export function CloseAllConnections():Promise<void>;

export function GetFieldsVOByTableID(arg1:number):Promise<Array<models.FieldInfoVO>>;

export function GetTableVOCacheByTableID(arg1:number):Promise<service.TableCacheVO|boolean>;

export function GetTablesVOByDatabaseID(arg1:number,arg2:any):Promise<Array<models.TableInfoVO>>;

export function InitCache(arg1:string):Promise<void>;

export function ListDatabasesByConfig(arg1:connect.Config):Promise<models.DBInfoVO>;

export function ParseViewSQL(arg1:string):Promise<Array<models.FieldInfoVO>>;

export function SetTableVOCacheByTableID(arg1:number,arg2:service.TableCacheVO):Promise<void>;

export function SyncDatabaseByID(arg1:number):Promise<void>;

export function SyncSchemaByID(arg1:number):Promise<void>;

export function SyncTableFieldsByTableID(arg1:number):Promise<void>;

export function TestConnection(arg1:connect.Config):Promise<void>;

export function UpdateFieldsSortByTableID(arg1:number,arg2:Array<number>):Promise<void>;
