// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearTableVOCacheByTableID(arg1) {
  return window['go']['api']['MetadatasAPI']['ClearTableVOCacheByTableID'](arg1);
}

export function CloseAllConnections() {
  return window['go']['api']['MetadatasAPI']['CloseAllConnections']();
}

export function GetFieldsVOByTableID(arg1) {
  return window['go']['api']['MetadatasAPI']['GetFieldsVOByTableID'](arg1);
}

export function GetTableVOCacheByTableID(arg1) {
  return window['go']['api']['MetadatasAPI']['GetTableVOCacheByTableID'](arg1);
}

export function GetTablesVOByDatabaseID(arg1, arg2) {
  return window['go']['api']['MetadatasAPI']['GetTablesVOByDatabaseID'](arg1, arg2);
}

export function InitCache(arg1) {
  return window['go']['api']['MetadatasAPI']['InitCache'](arg1);
}

export function ListDatabasesByConfig(arg1) {
  return window['go']['api']['MetadatasAPI']['ListDatabasesByConfig'](arg1);
}

export function ParseViewSQL(arg1) {
  return window['go']['api']['MetadatasAPI']['ParseViewSQL'](arg1);
}

export function SetTableVOCacheByTableID(arg1, arg2) {
  return window['go']['api']['MetadatasAPI']['SetTableVOCacheByTableID'](arg1, arg2);
}

export function SyncDatabaseByID(arg1) {
  return window['go']['api']['MetadatasAPI']['SyncDatabaseByID'](arg1);
}

export function SyncSchemaByID(arg1) {
  return window['go']['api']['MetadatasAPI']['SyncSchemaByID'](arg1);
}

export function SyncTableFieldsByTableID(arg1) {
  return window['go']['api']['MetadatasAPI']['SyncTableFieldsByTableID'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['api']['MetadatasAPI']['TestConnection'](arg1);
}

export function UpdateFieldsSortByTableID(arg1, arg2) {
  return window['go']['api']['MetadatasAPI']['UpdateFieldsSortByTableID'](arg1, arg2);
}
