// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {metadata} from '../models';
import {sqlite} from '../models';

export function DeleteCredentials(arg1:number):Promise<void>;

export function DeleteProject(arg1:number):Promise<void>;

export function GetAllCredentials():Promise<Array<metadata.Credentials>>;

export function GetAllProjects():Promise<Array<sqlite.Project>>;

export function Init():Promise<void>;

export function InsertCredentials(arg1:metadata.Credentials):Promise<metadata.Credentials>;

export function InsertProject(arg1:string,arg2:string):Promise<sqlite.Project>;

export function UpdateCredentials(arg1:metadata.Credentials):Promise<void>;

export function UpdateProject(arg1:sqlite.Project):Promise<void>;
