// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCredentials(arg1) {
  return window['go']['api']['SQLiteAPI']['DeleteCredentials'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['api']['SQLiteAPI']['DeleteProject'](arg1);
}

export function GetAllCredentials() {
  return window['go']['api']['SQLiteAPI']['GetAllCredentials']();
}

export function GetAllProjects() {
  return window['go']['api']['SQLiteAPI']['GetAllProjects']();
}

export function Init() {
  return window['go']['api']['SQLiteAPI']['Init']();
}

export function InsertCredentials(arg1) {
  return window['go']['api']['SQLiteAPI']['InsertCredentials'](arg1);
}

export function InsertProject(arg1, arg2) {
  return window['go']['api']['SQLiteAPI']['InsertProject'](arg1, arg2);
}

export function UpdateCredentials(arg1) {
  return window['go']['api']['SQLiteAPI']['UpdateCredentials'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['api']['SQLiteAPI']['UpdateProject'](arg1);
}
