// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDirectory(arg1) {
  return window['go']['api']['SystemServiceAPI']['CreateDirectory'](arg1);
}

export function Init(arg1) {
  return window['go']['api']['SystemServiceAPI']['Init'](arg1);
}

export function OpenDirectory() {
  return window['go']['api']['SystemServiceAPI']['OpenDirectory']();
}

export function PathExists(arg1) {
  return window['go']['api']['SystemServiceAPI']['PathExists'](arg1);
}
