// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function CreateDirectory(arg1:string):Promise<void>;

export function Init(arg1:context.Context):Promise<void>;

export function OpenDirectory():Promise<string>;

export function PathExists(arg1:string):Promise<boolean>;
